print("Arvin Rioflorido")
print("Nangka, Torrijos, Marinduque")
print("April 11, 2000")
print("Marinduque State College")
print("Bachelor of Science in Information Technology")
print("2F")
print("Hobbies:")
print("        Playing Online Games")
print("        Watching")
print("        Playing Basketball")
print("        Riding")
print("        Eating")